debug: false
spring:
  # 国际化配置
  messages:
    basename: i18n/message
  # 数据库
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/kingyan_plus?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

# 鉴权组件：https://sa-token.dev33.cn/doc/index.html#/use/config
sa-token:
  token-name: kysession
  token-style: simple-uuid
  #   max: 2147483648，cookie超时时间（s），不要超过int范围，虽然satoken是long
  timeout: 2592000
  is-concurrent: true
  is-share: false
  # 登陆前也能在satoken的session中存数据
  tokenSessionCheckLogin: false
  cookie:
    httpOnly: true

kingyan:
  # 前后端加密传输的密钥对
  sm2-key-pair:
    dynamic-key-pair: true
    # dynamic-key-pair为true时，多久更新一次密钥对。不要太小，最好大于10000(ms)
    timeout: 86400000
    # 如果dynamic-key-pair为false，则需要手动配置密钥
    # 如何生成见单元测试com.yunmuq.kingyanplus.sm.SMCryptoTest
#    private-key-hex:
#    public-key-hex:
#  captcha:
#    captchaTimeout: 60000
#    captchaLength: 5