debug: false
spring:
  # 国际化配置
  messages:
    basename: i18n/message
  # 数据库
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/kingyan_plus?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

# 鉴权组件：https://sa-token.dev33.cn/doc/index.html#/use/config
sa-token:
  token-name: kysession
  token-style: simple-uuid
  #   max: 2147483648，cookie超时时间（s），不要超过int范围，虽然satoken是long
  timeout: 2592000
  is-concurrent: true
  is-share: false
  # 登陆前也能在satoken的session中存数据
  tokenSessionCheckLogin: false
  cookie:
    httpOnly: true

# 如何生成见单元测试com.yunmuq.kingyanplus.sm.SMCryptoTest
sm2-key-pair:
  private-key-hex:
  public-key-hex: