debug: false
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/kingyan?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver